package entity;
// Generated Apr 3, 2019 9:07:43 AM by Hibernate Tools 4.3.1



/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable {


     private String username;
     private String password;
     private String fullname;
     private int age;
     private String city;
     private String gender;
     private String profession;
     private String fatherName;
     private String fatherProfession;
     private String motherName;
     private String motherProfession;
     private String education;
     private double height;
     private String address;
     private String about;

    public Profile() {
    }

    public Profile(String username, String password, String fullname, int age, String city, String gender, String profession, String fatherName, String fatherProfession, String motherName, String motherProfession, String education, double height, String address, String about) {
       this.username = username;
       this.password = password;
       this.fullname = fullname;
       this.age = age;
       this.city = city;
       this.gender = gender;
       this.profession = profession;
       this.fatherName = fatherName;
       this.fatherProfession = fatherProfession;
       this.motherName = motherName;
       this.motherProfession = motherProfession;
       this.education = education;
       this.height = height;
       this.address = address;
       this.about = about;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }
    public String getFatherProfession() {
        return this.fatherProfession;
    }
    
    public void setFatherProfession(String fatherProfession) {
        this.fatherProfession = fatherProfession;
    }
    public String getMotherName() {
        return this.motherName;
    }
    
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }
    public String getMotherProfession() {
        return this.motherProfession;
    }
    
    public void setMotherProfession(String motherProfession) {
        this.motherProfession = motherProfession;
    }
    public String getEducation() {
        return this.education;
    }
    
    public void setEducation(String education) {
        this.education = education;
    }
    public double getHeight() {
        return this.height;
    }
    
    public void setHeight(double height) {
        this.height = height;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }




}


